# workflow name
name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    name: deploy aws
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.8

      - name: Set ssh keys for github remote download
        working-directory: tests/
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_GITHUB }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Setup Dependencies
        working-directory: tests/
        run:  go get -v -t -d && go mod tidy

      - name: Run Go Tests
        working-directory: tests/
        run: |
          go test -v
